services:
  - type: web
    name: ai-dungeon-master-game
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class sync -w 1 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /
    autoDeploy: true
    plan: free
    staticOutboundIP: true
