services:
  - type: web
    name: ai-dungeon-master
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_minimal:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
